import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=' min-h-screen h-full bg-slate-950 text-white  mx-auto flex flex-col  w-full'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

